"use client";

import type { FormEvent } from "react";
import type { CollabType } from "@/lib/api";

type Props = { types: CollabType[]; newTitle: string; savingType: boolean; editingType: number | null; editingTitle: string; onNewTitleChange: (value: string) => void; onCreate: (event: FormEvent<HTMLFormElement>) => void; onEditingTitleChange: (value: string) => void; onStartEditing: (type: CollabType) => void; onSaveTitle: (type: CollabType) => void; onToggle: (type: CollabType) => void; };

export default function CollabTypesSection({ types, newTitle, savingType, editingType, editingTitle, onNewTitleChange, onCreate, onEditingTitleChange, onStartEditing, onSaveTitle, onToggle }: Props) {
  return <section className="mt-24 border-t border-white/10 pt-10"><div className="grid gap-10 lg:grid-cols-[.6fr_1.4fr]"><div><p className="eyebrow">Configuração</p><h2 className="mt-3 text-3xl font-bold tracking-[-.05em]">Tipos de collab</h2><p className="mt-3 max-w-sm text-sm leading-6 text-fog">Opções inativas não aparecem no formulário público. Propostas existentes continuam preservadas.</p><form onSubmit={onCreate} className="mt-7 flex gap-2"><input className="field" value={newTitle} onChange={(event) => onNewTitleChange(event.target.value)} placeholder="Novo tipo" maxLength={80} /><button className="button-primary" disabled={savingType}>Adicionar</button></form></div><div className="grid gap-px self-start border border-white/10 bg-white/10 sm:grid-cols-2">{types.map((type) => <div key={type.id} className="bg-[#101010] p-5">{editingType === type.id ? <div className="flex gap-2"><input className="field" value={editingTitle} onChange={(event) => onEditingTitleChange(event.target.value)} maxLength={80} /><button className="button-secondary" onClick={() => onSaveTitle(type)}>Salvar</button></div> : <div className="flex items-center justify-between gap-4"><div><p className="font-bold">{type.title}</p><p className={`mt-1 text-[10px] font-bold uppercase tracking-[.15em] ${type.active ? "text-emerald-300" : "text-fog"}`}>{type.active ? "Ativo" : "Inativo"}</p></div><div className="flex gap-2"><button className="button-secondary" onClick={() => onStartEditing(type)}>Editar</button><button className="button-secondary" onClick={() => onToggle(type)}>{type.active ? "Desativar" : "Ativar"}</button></div></div>}</div>)}</div></div></section>;
}
