"use client";

import { FormEvent, useEffect, useState } from "react";
import type { CollabType } from "@/lib/api";

type FormState = { brand_name: string; email: string; instagram: string; collab_type_id: string; proposed_date: string; pitch: string };
const initial: FormState = { brand_name: "", email: "", instagram: "", collab_type_id: "", proposed_date: "", pitch: "" };

export default function SubmissionForm() {
  const [types, setTypes] = useState<CollabType[]>([]); const [form, setForm] = useState(initial); const [error, setError] = useState(""); const [success, setSuccess] = useState(false); const [loading, setLoading] = useState(false); const today = new Date().toISOString().slice(0, 10);
  useEffect(() => { fetch("/api/collab-types").then((response) => response.ok ? response.json() : []).then(setTypes).catch(() => setTypes([])); }, []);
  function update(key: keyof FormState, value: string) { setForm((current) => ({ ...current, [key]: value })); setError(""); setSuccess(false); }
  function validate() { if (form.brand_name.trim().length < 2) return "Conta pra gente o nome da marca ou artista."; if (!/^\S+@\S+\.\S+$/.test(form.email)) return "Digite um email válido para a gente responder."; if (form.instagram.trim().length < 2) return "Informe o Instagram da marca ou artista."; if (!form.collab_type_id) return "Escolha um formato de collab."; if (!form.proposed_date) return "Escolha uma data pretendida."; if (form.pitch.trim().length < 20) return "Desenvolva um pouco mais a ideia (mínimo de 20 caracteres)."; if (form.pitch.length > 500) return "O pitch deve ter no máximo 500 caracteres."; return ""; }
  async function submit(event: FormEvent) { event.preventDefault(); const validation = validate(); if (validation) { setError(validation); return; } setLoading(true); setError(""); try { const response = await fetch("/api/submissions", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ ...form, collab_type_id: Number(form.collab_type_id) }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Não foi possível enviar sua proposta."); setSuccess(true); setForm(initial); } catch (submissionError) { setError(submissionError instanceof Error ? submissionError.message : "Não foi possível enviar sua proposta."); } finally { setLoading(false); } }
  return <div className="max-w-2xl">{success && <div className="mb-8 flex items-start gap-4 border border-white/20 bg-white p-5 text-ink"><span className="text-xl">✓</span><div><p className="text-sm font-bold uppercase tracking-[.15em]">Proposta recebida.</p><p className="mt-1 text-sm text-black/60">Obrigado por compartilhar. A gente vai olhar com atenção.</p></div></div>}{error && <div role="alert" className="mb-8 border border-red-400/50 bg-red-950/30 p-4 text-sm text-red-200">{error}</div>}<form onSubmit={submit} className="grid gap-7 sm:grid-cols-2"><label className="sm:col-span-2"><span className="eyebrow mb-2 block text-white/60">01 / Seu nome ou marca *</span><input className="field" value={form.brand_name} onChange={(e) => update("brand_name", e.target.value)} placeholder="Ex: Studio Norte" maxLength={100} /></label><label><span className="eyebrow mb-2 block text-white/60">02 / Email *</span><input className="field" type="email" value={form.email} onChange={(e) => update("email", e.target.value)} placeholder="hello@studio.com" /></label><label><span className="eyebrow mb-2 block text-white/60">03 / Instagram *</span><input className="field" value={form.instagram} onChange={(e) => update("instagram", e.target.value)} placeholder="@seuinstagram" maxLength={100} /></label><label><span className="eyebrow mb-2 block text-white/60">04 / Formato *</span><select className="field" value={form.collab_type_id} onChange={(e) => update("collab_type_id", e.target.value)}><option value="">Selecione uma opção</option>{types.map((type) => <option key={type.id} value={type.id}>{type.title}</option>)}</select></label><label><span className="eyebrow mb-2 block text-white/60">05 / Data pretendida *</span><input className="field" type="date" min={today} value={form.proposed_date} onChange={(e) => update("proposed_date", e.target.value)} /></label><label className="sm:col-span-2"><span className="eyebrow mb-2 flex justify-between text-white/60"><span>06 / A ideia *</span><span>{form.pitch.length} / 500</span></span><textarea className="field min-h-36 resize-y" value={form.pitch} onChange={(e) => update("pitch", e.target.value)} placeholder="O que podemos construir juntos?" maxLength={500} /></label><div className="sm:col-span-2 flex items-center justify-between gap-5 border-t border-white/10 pt-7"><p className="max-w-xs text-xs leading-5 text-fog">Respondemos apenas para projetos que avançam para a próxima etapa.</p><button className="button-primary shrink-0" disabled={loading}>{loading ? "Enviando..." : "Enviar proposta ↗"}</button></div></form></div>;
}
