"use client";

import { FormEvent, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import type { CollabType, Submission, SubmissionResponse } from "@/lib/api";
import OverviewSection from "./OverviewSection/OverviewSection";
import MetricsSection from "./MetricsSection/MetricsSection";
import SubmissionsSection from "./SubmissionsSection/SubmissionsSection";
import CollabTypesSection from "./CollabTypesSection/CollabTypesSection";
import Navbar from "@/components/Navbar/Navbar";

export default function AdminPage({ initialData, initialTypes }: { initialData: SubmissionResponse; initialTypes: CollabType[] }) {
  const router = useRouter();
  const [result, setResult] = useState(initialData); const [types, setTypes] = useState(initialTypes); const [status, setStatus] = useState(""); const [search, setSearch] = useState(""); const [page, setPage] = useState(1); const [notice, setNotice] = useState(""); const [newTitle, setNewTitle] = useState(""); const [savingType, setSavingType] = useState(false); const [editingType, setEditingType] = useState<number | null>(null); const [editingTitle, setEditingTitle] = useState(""); const [loading, setLoading] = useState(false);

  useEffect(() => { if (page === 1 && !status && !search) return; void load(); }, [page, status]);
  async function load() { setLoading(true); const params = new URLSearchParams({ page: String(page), limit: "10" }); if (status) params.set("status", status); if (search) params.set("search", search); const response = await fetch(`/api/submissions?${params}`); if (response.status === 401) { router.push("/admin/login"); return; } if (response.ok) setResult(await response.json()); setLoading(false); }
  function searchSubmit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPage(1); void load(); }
  async function changeStatus(item: Submission, nextStatus: "confirmed" | "cancelled") { const previous = result.data; setNotice(""); setResult((current) => ({ ...current, data: current.data.map((entry) => entry.id === item.id ? { ...entry, status: nextStatus } : entry), counts: { ...current.counts, [item.status]: Math.max(0, current.counts[item.status] - 1), [nextStatus]: current.counts[nextStatus] + 1 } })); const response = await fetch(`/api/submissions/${item.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: nextStatus }) }); if (!response.ok) { setResult((current) => ({ ...current, data: previous })); setNotice("Não foi possível atualizar o status."); } else setNotice("Status atualizado."); }
  async function logout() { await fetch("/api/auth/logout", { method: "POST" }); router.push("/admin/login"); router.refresh(); }
  async function createType(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!newTitle.trim()) return; setSavingType(true); const response = await fetch("/api/collab-types", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title: newTitle }) }); const payload = await response.json(); if (response.ok) { setTypes((current) => [...current, payload]); setNewTitle(""); setNotice("Tipo criado."); } else setNotice(payload.error || "Não foi possível criar o tipo."); setSavingType(false); }
  async function toggleType(type: CollabType) { const response = await fetch(`/api/collab-types/all?id=${type.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ active: !type.active }) }); if (response.ok) { const updated = await response.json(); setTypes((current) => current.map((entry) => entry.id === type.id ? { ...entry, ...updated } : entry)); setNotice(updated.active ? "Tipo ativado." : "Tipo desativado."); } else setNotice("Não foi possível atualizar o tipo."); }
  async function saveTypeTitle(type: CollabType) { const title = editingTitle.trim(); if (title.length < 3) { setNotice("O título deve ter pelo menos 3 caracteres."); return; } const response = await fetch(`/api/collab-types/all?id=${type.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title }) }); const payload = await response.json(); if (response.ok) { setTypes((current) => current.map((entry) => entry.id === type.id ? { ...entry, ...payload } : entry)); setEditingType(null); setNotice("Título atualizado."); } else setNotice(payload.error || "Não foi possível atualizar o título."); }

  return <main className="min-h-screen bg-ink"><Navbar variant="admin" onLogout={logout} /><div className="mx-auto max-w-[1500px] px-6 py-12 lg:px-10 lg:py-16"><OverviewSection notice={notice} /><MetricsSection counts={result.counts} /><SubmissionsSection result={result} status={status} search={search} page={page} loading={loading} onSearchChange={setSearch} onSearchSubmit={searchSubmit} onStatusChange={(value) => { setStatus(value); setPage(1); }} onPreviousPage={() => setPage((current) => current - 1)} onNextPage={() => setPage((current) => current + 1)} onChangeStatus={changeStatus} /><CollabTypesSection types={types} newTitle={newTitle} savingType={savingType} editingType={editingType} editingTitle={editingTitle} onNewTitleChange={setNewTitle} onCreate={createType} onEditingTitleChange={setEditingTitle} onStartEditing={(type) => { setEditingType(type.id); setEditingTitle(type.title); }} onSaveTitle={saveTypeTitle} onToggle={toggleType} /></div></main>;
}
